### PR TITLE
Linux support!

### PR DESCRIPTION
**Pull request by jon-dez**
The past week has been pretty boring not going to lie, due to some illness placing restrictions on how much we could move around and such.

But I have been keeping myself busy working on making The Joy-Con Toolkit compatible with linux platforms, because why not!

Here is a screen capture:

(Yes that's me. In a selfie.)

It's still in the early stages so it is obviously lacking some features that the original tool has, but It will eventually get there.

One take away from the screen capture is that the toolkit is no longer dependant on Winform's UI framework. I took time to look over relevant sections of the original source code to understand how it all worked together. I seperated some of the useful code that was spliced into the Formjoy.h file and placed them into a seperate file, and did some "#define" trickery to isolate the winform calls intertwined within the jctool.cpp file. I did other stuff, albiet very "hackily", so that I could get it working. Also, because most of the function calls around Joy-Con Toolkit are independant from any UI framework,  it is possible to use it as an API.

There are improvements I could make, however I wanted to share what I have so far.

Feedback is appreciated!

### CODE REVIEW

**Comment by jon-dez** [comment]
BTW, the first commit was a mistake and was eventually reverted further down the line as I realized the error!

**Comment by CTCaer** [comment]
Hey. I don't have time these days to review, but I wanted to tell you that I see the progress from time to time and thanks for the PR.

It's great that you are making this an api that can work everywhere and be able to cope with the unreadable 5AM code.

I also wanted to tell you that the toolkit looks follow a similar color scheme with HOS. But I suppose that this is irrelevant for now and with what you want to achieve.
The most important for now is to make it workable to all platforms (and I suppose that this PR already runs in Mac OS also).

Thanks again for the PR!

**Comment by jon-dez** [comment]
Greetings, CTCaer!

The ultimate goal is to make this an API, so that it will become The Joy-Con Toolkit [API], but I also want to provide a nice demo program to show off the capabilities. Since you mentioned the tool attempts to follow the color scheme of HOS I will put that on the list of things to do since your original tool had a pretty good UI, and I want to be faithful to that.

Thanks for the comment!

**Comment by jon-dez** [comment]
I made a small mockup trying to emulate HOS's settings page. I still have to fiddle around with some settings to make it match up.

jctool_kit_hos

**Comment by nusco** [comment]
This is awesome. Thank you, @jon-dez! (And of course, thank you @CTCaer for the original tool!)

**Comment by jon-dez** [comment]
@nusco Not a problem, and thanks!

**Pull request closed without merging**
