### PR TITLE
Fixed mistake in ordering of accel data bytes

### PR DESCRIPTION
**Pull request by wormyrocks**
This seems like it's just a typo but worth pointing out unless you're doing something I don't understand. Thanks for your advice on the other thread

### CODE REVIEW

**Comment by CTCaer** [comment]
Thank you for pointing it out, it's a copy paste typo.

Some new info from seeing the correct values now:
Now Factory 6-Axis calibration data makes more sense.

For example I have these in one controller:
6-Axis Factory:
FF13 00D2 00EF
4000 4000 4000
**000C FFEF FFD4**
343B 343B 343B

The 3rd line almost matches with the Accelerometer range of values I now get for when the Joy-Con stays still on my desk.
I will do a manual 6-axis calibration and check again if it completely matches with user cal.
We now need to find the other 3 what they are used for. 
Probably the first one is Gyro center position and the 2nd/4th are maximum rotation/maximum acceleration.

**Comment by CTCaer** [comment]
LGTM

**Comment by wormyrocks** [comment]
Are the calibration values the ones read from the SPI flash?

Also I've read in different places that the gyro/accel data is packed as floats or uint16 values. You also mentioned that the values are sent three times - is that true? If that's the case - what's the purpose of the bytes beyond 0x24 in the input reports?

**Comment by CTCaer** [comment]
Yes. And if you calibrated the sticks or the sensor, user calibration also shows up in my app.

They are little-endian uint16_t but the real data that is stored in them is a half-precision float.

So you need to cast them in the most efficient way.
Sth like this (untested):
```
float sensor_uint16_to_float(uint16_t a) {
    float b;
    uint32_t c = a << 16;
    char* cPointer = (char*)&c, *bPointer = (char*)&b;
    memcpy(bPointer, cPointer, sizeof(c));
    return b;
}
```

Yes, Joy-Con packet contains 3 times the sensor data. 

As these are normally different, my theory is the following:
The data is pushed every 15ms. Every group is with 5ms difference. This minimizes bluetooth traffic and somewhat keeps a fast precision.

If this is true, one way to find which one is the 5ms values and which is the 15ms, is to swing the controller on the +Axis and catch a value when you are accelerating. The biggest value is 15ms the smallest the 5ms.

I don't know about the Pro (8ms) through.

**Comment by CTCaer** [comment]
Just tested the code above. It does not work, because it produces out of range floats.
My assumptions were false.

**These really are int16_t**. 
But haven't researched how they are converted to float. 
Maybe the x4000 and x343B values are used to converted them.

**Pull request merged**
